openapi: 3.0.0
info:
  title: OnlinePOS Vat Rate Rest API (ON REFS!)
  description: This API allows 3rd parties to manage Vat Rates Only<br><br>Registration is required
  termsOfService: 'https://legal.onlinepos.com/da/api-terms/'
  contact:
    name: API Support
    url: 'https://legal.onlinepos.com/da/api-support/'
    email: info@onlinepos.dk
  license:
    name: unlicensed
    url: 'https://legal.onlinepos.com/da/api-license/'
  version: 1.0.22-test
servers:
  - url: '{protocol}://{products_base_url}'
    description: Test defined URL for test system
    variables:
      products_base_url:
        default: 'localhost:8667'
      protocol:
        enum:
          - http
          - https
        default: http
      bearerToken:
        default: 5|JstqiRiJJvJMK48PKQrAGcH2V70GzuCvnEjDmiyx
      client_id:
        default: demo
      venue:
        default: '9000'
security:
  - bearerAuth: []
tags:
  - name: Vat Rates
    description: Calls that create and manipulate vat rates
paths:
  /vat-rates:
    post:
      $ref: ./paths/vat-rates.yaml#/vat-rates/post
    get:
      $ref: ./paths/vat-rates.yaml#/vat-rates/get
      tags:
        - Vat Rates
  '/vat-rates/{id}':
    get:
      $ref: './paths/vat-rates.yaml#/vat-rates~1{id}/get'
      tags:
        - Vat Rates
    put:
      $ref: './paths/vat-rates.yaml#/vat-rates~1{id}/put'
    delete:
      $ref: './paths/vat-rates.yaml#/vat-rates~1{id}/delete'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
