get:
  summary: Configuration for the current user
  operationId: get-me-config
  description: Returns configuration for the current user
  tags:
    - User
  parameters:
    - $ref: '../../v1.yaml#/components/parameters/acceptInHeader'
  responses:
    '200':
      $ref: '../users/components.yaml#/responses/UserConfigResponse'
    '401':
      $ref: '../../v1.yaml#/components/responses/Unauthorized'
    '406':
      $ref: '../../v1.yaml#/components/responses/NotAcceptable'
    '415':
      $ref: '../../v1.yaml#/components/responses/UnsupportedMediaType'
    '500':
      $ref: '../../v1.yaml#/components/responses/ServerError'
