sales_product_id:
    description: The ID of the sales product
    name: id
    in: path
    required: true
    schema:
        type: integer
        example: 1001

vat_rate_id:
    description: An ID of the vat rate
    name: id
    in: path
    required: true
    schema:
        type: integer
        example: 2

venue_id:
    description: An ID of a specific company
    name: venue
    in: query
    required: true
    schema:
        type: integer
        example: 9000
